### ISSUE TITLE
What's this statik thing?

### ISSUE THREAD

**Issue by bwreilly** [democratizr/immigration-faq#6]
https://getstatik.com

Good thing initially - the models are not static. You can build whatever (as opposed to typical blog models in these things).

Quickstart: https://github.com/thanethomson/statik/wiki/Walkthrough

**Comment by bwreilly** [comment]
Well this is kinda neat

> Statik uses SQLAlchemy under the hood to build up an in-memory SQLite database from which your views and templates can execute queries. You define your models in YAML format.

**Comment by bwreilly** [comment]
So you

1. Define some `models` in YAML
2. Throw some YAML/Markdown in `data/<ModelName>` - one file per instance
3. Write some views with YAML

```yaml
path: /
template: home     # The .html is automatically added by Statik
context:
  static:
    page-title: Welcome to my blog
  dynamic:
    posts: session.query(Post).all()
```

4. Make some Jinja templates - they can reference info they get from the views 

```jinja
{% extends "base.html" %}

{% block body %}
  <h1>Welcome to My Blog!</h1>
  <p>These are my latest posts</p>
  <ul>
    {% for post in posts %}
      <li><a href="{% url "post", post %}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}
```

It's pretty neat
